source 'https://rubygems.org'

gem 'cucumber', '3.1.2'
gem 'parallel_tests', '2.26.2'
gem 'parallel', '1.12.1'
gem 'pry'
gem 'pry-nav'
gem 'rspec'
gem 'selenium-webdriver', '3.141.0'
gem 'yard-cucumber'
gem 'yard'
gem 'rake'
gem 'httparty'
gem 'crack'
gem 'nokogiri', '1.8.0'
gem 'capybara', '3.10.0'
gem 'rspec-expectations'
gem 'axe-matchers'
gem 'report_builder'
